### ISSUE TITLE
move coreference classifier into sentence_classifier level

### ISSUE THREAD

**Issue by alabrashJr** [emerging-welfare/emw_pipeline_nf#13]
coreference is now placed in out_to_csv.py script where it's work after the pipeline is completed. 
The sentences(either protest positive or have trigger token) of each document are formatted and given as input to the classifier. if the output of the classifier gives any group of coreference the group merged and reported in the detailed report. 

Putting the coreference model before semantic classifiers might improve the performance of those classifiers since the coreference sentences will be joined the sentences that point to the same event which will make them more which makes them richer content.

**Comment by OsmanMutlu** [comment]
Resolved in 6b82f668aab2e9605180525fccbdd647fe02d305
