### ISSUE TITLE
pipeline installation is misleading

### ISSUE THREAD

**Issue by fatihbeyhan** [emerging-welfare/emw_pipeline_nf#24]
installation.sh has to be reviewed. It gives misleading outputs. Even after one of installation steps is not properly completed, it prints out an approval that says the step is completed and proceeds to the next one.

**Comment by OsmanMutlu** [comment]
Please specify the exact part you are referring to. A line number would be sufficient.

**Comment by OsmanMutlu** [comment]
Resolved with fd35f4a610eb78142ce9da71907e0815fac6ee55
Install.sh script now exists when it encounters an error, and prints the error and its line.
